### ISSUE TITLE
audit_record_objs is not pattern matching

### ISSUE THREAD

**Issue by utdrmac** [mcafee/mysql-audit#116] opened 2015-06-17 16:27 UTC
The setting *audit_record_objs* does not appear to be pattern matching on * but instead treating it literally.

The documentation says "wildcards are supported" and so one might set this as such:

```
mysql> SET GLOBAL audit_record_objs = "*.*";
```

in order to "log all tables on all databases"

But in this case, the element to the right of the dot is being treated literally and only queries that have a derived table (which results in a * [object in the audit](https://github.com/mcafee/mysql-audit/issues/114)) are being logged.

Test via the following:
```
 CREATE DATABASE percona; use percona;
 CREATE TABLE foo (id INT);
 SET GLOBAL audit_record_objs = "*.*";
 SET GLOBAL audit_record_cmds = "";
 INSERT INTO foo VALUES (1);
 -- Nothing logged
 SELECT * FROM foo;
 -- Nothing logged
 SELECT * FROM (SELECT * FROM foo) a;
 -- Logged entry
 SET GLOBAL audit_record_objs = "";
 INSERT INTO foo VALUES (888);
 -- Logged entry
 SET GLOBAL audit_record_objs = "percona.*";
 INSERT INTO foo VALUES (888);
 -- Logged entry
 SET GLOBAL audit_record_objs = "*.foo";
 INSERT INTO foo VALUES (889);
 -- Logged entry
```

Suggested fix: Correct the documentation to explain this caveat or correct code to properly pattern match on *.*

**Comment by guylichtman** [comment] 2015-06-23 06:31
Hi Matthew,

This is by design. If you want to record all objects just don't set the
`audit_record_objs` parameter. If it is not set then all objects are
recorded so there is no need for `*.*`. The wildcard support is meant for
usage in cases such `*.foo` or `percona.*`.

**Comment by guylichtman** [comment] 2015-07-04 05:21
Closing the issue as this is by design.

**Closed by guylichtman** 2015-07-04 05:21 UTC
