### ISSUE TITLE
@@warning_count and SHOW WARNINGS empty for NOTE

### ISSUE THREAD

**Issue by atze234** [mcafee/mysql-audit#137] opened 2016-02-04 11:42 UTC
Hi, 

with audit Plugin loaded SHOW WARNINGS and select @@warning_count doesn't report any NOTES to me, when there should be NOTES:

Server version: 5.5.47-0+deb7u1-log (Debian)

mysql> use mysql
mysql> create table if not exists user (id int);
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> select @@warning_count;
+-----------------+
| @@warning_count |
+-----------------+
|               0 |
+-----------------+
1 row in set (0.01 sec)

Without Plugin loaded:
mysql> create table if not exists user (id int);
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> select @@warning_count;
+-----------------+
| @@warning_count |
+-----------------+
|               1 |
+-----------------+
1 row in set (0.00 sec)

The reported Note should be:
mysql> show warnings;
+-------+------+-----------------------------+
| Level | Code | Message                     |
+-------+------+-----------------------------+
| Note  | 1050 | Table 'user' already exists |
+-------+------+-----------------------------+

When i produce a WARNING ( select abs("a");) the warning is reported correctly.
I'm using the latest Plugin Version 1.0.9-545 with mysql 5.5.47 on Debian 7. 

Thanks for your help
Jörg

**Comment by atze234** [comment] 2016-02-04 13:10
I tried with latest Release Version 1.0.8-527 and the reported Offsets from 1.0.9-545 
(audit_offsets=6120, 6168, 3792, 4288, 88, 2592, 96, 0, 32, 104, 120, 6264)

Problem is still there then, so i think its related to 5.5.47 (Debian) or the offsets.

**Comment by aharonrobbins** [comment] 2016-02-09 12:14
Thanks for the report. We will try to investigate.

**Comment by guylichtman** [comment] 2016-04-08 13:45
@atze234,

I just tried out your exact version: 5.5.47-0+deb7u1-log (Debian) and didn't see this reproduce with the latest plugin release: 1.0.9-585.

It might be something specific to your configuration. Can you send out your my.cnf configuration. Also can you include the mysql-error.log. It may contain some more info to understand your configuration.

**Comment by atze234** [comment] 2016-04-13 08:17
@guylichtman ,

may i send you the Information in a private channel anywhere?

**Comment by aharonrobbins** [comment] 2016-04-13 08:20
Please send to me as well; Guy and I work in the same office and it’s likely that I will end up working on it.

Thanks,

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]

**Comment by guylichtman** [comment] 2016-05-20 14:12
Just to update, we had some email exchanges with @atze234  and from what we see the issue is happening on a specific system they have. It is not reproducing on other system with a similar setup. Unfortunately the system is not available for debugging. We are planning a small architecture change which may resolve this issue in the future. 

In the mean time, if any one encounters the same behavior please update this issue.

**Comment by atze234** [comment] 2016-05-26 08:17
Hi,
the Problem just disappeared with Debian mysql 5.5.49 and Audit Plugin 601.

**Comment by guylichtman** [comment] 2016-05-29 10:35
Closing the issue. If it does come up again. Feel free to reach out.

**Closed by guylichtman** 2016-05-29 10:35 UTC
