### ISSUE TITLE
In mysql on solaris 10, can't install audit plugin

### ISSUE THREAD

**Issue by ajaajalee** [mcafee/mysql-audit#97] opened 2015-01-06 05:41 UTC
I did success compile solairs 10 x64 this audit plugin 1.0.7
but, in mysql can't install audit plugin.

mysql> INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so';
ERROR 1126 (HY000): Can't open shared library '/usr/local/mysql5.5.27-ndb7.2.8/lib/plugin/libaudit_plugin.so' (errno: 2 ld.so.1: mysqld: fatal: relocation error: file /usr/local/mysql5.5.27-ndb7.2.8/lib/plugin/libaudit_plugin.so: symbol _Z18log_slo)

Do you know how to solve this error?

**Comment by guylichtman** [comment] 2015-01-06 11:24
Not too sure why you are encountering this error. We never tried supporting Solaris so I guess there is some work needed to get it to fully function. Can you share how you got the plugin to compile on solaris. Maybe that can help.

**Comment by ajaajalee** [comment] 2015-01-07 04:22
Thannks for you reply.

I encountred two problem during complie on solaris.
firstly, in solaris strcasestr function not exist. and then, i add in audit_plugin.cc.
strcasestr(const char *s, const char *find)
{
	char c, sc;
	size_t len;

	if ((c = *find++) != 0) {
		c = (char)tolower((unsigned char)c);
		len = strlen(find);
		do {
			do {
				if ((sc = *s++) == 0)
					return (NULL);
			} while ((char)tolower((unsigned char)sc) != c);
		} while (strncasecmp(s, find, len) != 0);
		s--;
	}
	return ((char *)s);
}

secondly, ld of solaris not compatible. and then modified in src/Makefile
libaudit_plugin_la_LDFLAGS = -module -Wl,-M,MySQLPlugin.map

no problmen to compile on solaris this plugin with this two solution.
but, It failed INSTALL PLUGIN AUDIT SONAME 'libaudit_plugin.so' on mysql.

**Comment by guylichtman** [comment] 2015-01-08 21:22
Thanks for specifying the details for getting the plugin to compile on Solaris. Solaris support is not currently on our roadmap, I am leaving this issue open and if anyone else is looking for a Solaris solution please add a comment here.

**Comment by kubo** [comment] 2016-08-04 15:20
@ajaajalee 
Could you post the output of the following commands?
```shell
$ nm /usr/local/mysql5.5.27-ndb7.2.8/lib/plugin/libaudit_plugin.so | grep log_slow_statement
$ nm /usr/local/mysql5.5.27-ndb7.2.8/bin/mysqld | grep log_slow_statement
```
IMO, `libaudit_plugin.so` was compiled by gcc and `mysqld` was compiled by Oracle Solaris Studio.

> ... relocation error: file /usr/local/mysql5.5.27-ndb7.2.8/lib/plugin/libaudit_plugin.so: symbol _Z18log_slo)

`_Z18log_slo` looks like `_Z18log_slow_statementP3THD`, which is the mangled name of `void log_slow_statement(THD *thd)` by gcc.
If `mysqld` was compiled by Oracle Solaris Studio, the same function was mangled to different name.
See [here](https://en.wikipedia.org/wiki/Name_mangling#How_different_compilers_mangle_the_same_functions). (`SunPro CC` in the link is old name of Oracle Solaris Studio.)
As a result,  `libaudit_mysql.so` tried to reference `_Z18log_slow_statementP3THD` but it wasn't defined anywhere.

**Comment by jadhavmanoj** [comment] 2016-08-10 05:19
Hi

I am using ubuntu 14.04 and mysql - 5.5.50-0ubuntu0.14.04.1

I tried to execute below command to generate offset but it returns error.

manoj@manoj-Lenovo-B50-80:~$ ../offset-extract.sh /usr/sbin/mysqld  
//offsets for: /usr/sbin/mysqld (5.5.50-0ubuntu0.14.04.1)
offsets.gdb:2: Error in sourced command file:
No symbol table is loaded.  Use the "file" command.,

How can I resolved this issue?

**Comment by ajaajalee** [comment] 2016-08-10 05:50
@kubo
thans your replay.
but I am sorry that currently I don't use solaris.

**Comment by aharonrobbins** [comment] 2016-08-10 07:44
Hi.

The problem is that /usr/sbin/mysqld is stripped – it has no symbols.

Please see the discussion in https://github.com/mcafee/mysql-audit/issues/136 which may be useful.

You can also try installing the mysql-server-5.5-dbgsym package and see if it brings you a version of mysqld that isn’t stripped. If so, you would run the offset-exract.sh script with two arguments: the path to mysqld and the path to the file with the debug symbols.

I will try to set up an Ubuntu 14.04 system and test this myself sometime soon.

Thanks,

Aharon Robbins

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]

**Comment by jadhavmanoj** [comment] 2016-08-21 04:36
@aharonrobbins 

Thanks for your reply

**Comment by aharonrobbins** [comment] 2016-08-21 09:16
I spent quite some time trying to determine how to install and use the -dbgsym package for mysql-server on Ubuntu 14.04. I was not able to use any of the files it installed as the symbol file for use with the extract_offset script.  I think your best bet will be to build mysql-server from Ubuntu sources and then extract the offsets from the version you compile yourself.

Best of luck,

Aharon

**Comment by aharonrobbins** [comment] 2017-02-13 14:47
Closing this issue.

**Closed by aharonrobbins** 2017-02-13 14:47 UTC
