### ISSUE TITLE
Error with offsets for mysql version 5.6.31

### ISSUE THREAD

**Issue by megol** [mcafee/mysql-audit#156] opened 2017-01-10 22:23 UTC
Hello,

I have a problem with plugin installation on mysql 5.6.31, I have the following errors:

2017-01-10 22:25:20 11932 [Warning] option 'audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-10 22:25:20 11932 [Warning] option 'plugin-audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-10 22:25:20 11932 [Note] Audit Plugin: starting up. Version: 1.0.8 , Revision: 527 (64bit). AUDIT plugin interface version: 769 (0x301). MySQL Server version: 5.6.31-log.
2017-01-10 22:25:20 11932 [Note] Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 1 offsets_by_version: 1
2017-01-10 22:25:20 11932 [Note] Audit Plugin: mysqld: /usr/sbin/mysqld (b919af973cb0f7c6c7c97a77934deb58)
2017-01-10 22:25:20 11932 [Note] Audit Plugin: Couldn't find proper THD offsets for: 5.6.31-log
2017-01-10 22:25:20 11932 [ERROR] Plugin 'AUDIT' init function returned error.
2017-01-10 22:25:20 11932 [ERROR] Plugin 'AUDIT' registration as a AUDIT failed.
2017-01-10 22:25:20 11932 [Note] Shutting down plugin 'AUDIT'
2017-01-10 22:25:20 11932 [Note] Audit Plugin: deinit

also offset_extract.sh script doesn't help me to set correct ones:

# ./offset-extract.sh /usr/sbin/mysqld
//offsets for: /usr/sbin/mysqld (5.6.31)
{"5.6.31","b919af973cb0f7c6c7c97a77934deb58"offsets.gdb:7: Error in sourced command file:
No symbol table is loaded.  Use the "file" command.,

Could you please help me to set exact offsets ?

Regards,
Marcel

**Comment by aharonrobbins** [comment] 2017-01-11 07:54
Hi. Please see the discussion at [Troubleshooting](https://github.com/mcafee/mysql-audit/wiki/Troubleshooting).  You don't state what Linux distribution you're using, but it looks like it's one where `mysqld` is distributed without debug symbols, in which case you may have to build from source.

I hope this helps,

Aharon

**Comment by guylichtman** [comment] 2017-01-11 08:03
@megol, try using the latest version of the plugin. It already has the offsets for 5.6.31 and it may work for you without extracting the offsets.

**Comment by megol** [comment] 2017-01-11 12:11
Hello, 

I'm using Red Hat distribution:
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)

and the mysqld version 5.6.31_log 

this server works in galera cluster as it has lib imported in my.cnf 
wsrep_provider = /usr/lib64/galera-3/libgalera_smm.so

@guylichtman I was using this version of plugin: https://bintray.com/mcafee/mysql-audit-plugin/download_file?file_path=audit-plugin-mysql-5.6-1.1.1-660-linux-x86_64.zip

it's the latest one I guess?

thanks

**Comment by guylichtman** [comment] 2017-01-11 12:16
In the log you provided it says: 1.0.8:

2017-01-10 22:25:20 11932 [Note] Audit Plugin: starting up. Version: 1.0.8
, Revision: 527 (64bit).

Please provide latest log of 1.1.1.

**Comment by megol** [comment] 2017-01-11 12:20
Hi @guylichtman 

same for 1.1.1 I tried almost each of release version:

```
2017-01-11 13:19:41 11932 [Warning] option 'audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-11 13:19:41 11932 [Warning] option 'plugin-audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-11 13:19:41 11932 [Note] Audit Plugin: starting up. Version: 1.1.1 , Revision: 660 (64bit). AUDIT plugin interface version: 769 (0x301). MySQL Server version: 5.6.31-log.
2017-01-11 13:19:41 11932 [Note] Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 1 offsets_by_version: 1
2017-01-11 13:19:41 11932 [Note] Audit Plugin: mysqld: /usr/sbin/mysqld (b919af973cb0f7c6c7c97a77934deb58)
2017-01-11 13:19:41 11932 [ERROR] Audit Plugin: Offsets: 5.6.31 (f0ca4df6f1b6f3e31aa4a1a94a94d84d) match thread validation check fails with value: 0. Skipping offset.
2017-01-11 13:19:41 11932 [ERROR] Audit Plugin: Offsets: 5.6.31 (f0ca4df6f1b6f3e31aa4a1a94a94d84d) match thread validation check fails with value: 0. Skipping offset.
2017-01-11 13:19:41 11932 [Note] Audit Plugin: Couldn't find proper THD offsets for: 5.6.31-log
2017-01-11 13:19:41 11932 [ERROR] Plugin 'AUDIT' init function returned error.
2017-01-11 13:19:41 11932 [ERROR] Plugin 'AUDIT' registration as a AUDIT failed.
2017-01-11 13:19:41 11932 [Note] Shutting down plugin 'AUDIT'
2017-01-11 13:19:41 11932 [Note] Audit Plugin: deinit
```

thanks.

**Comment by aharonrobbins** [comment] 2017-01-11 12:36
Please review the troubleshooting section I pointed to earlier. You can try setting `audit_validate_checksum=OFF` in the configuration file. If that does not work, you will have to see if you can download debugging symbols for your version of MySQL, or else rebuild from source to extract offsets.

Please review that Wiki page in detail.

Thanks.

**Comment by megol** [comment] 2017-01-11 13:01
Hi @aharonrobbins 

I tried with your advise however by setting only:

audit_validate_checksum=OFF

mysql cannot start, but when I set:

audit_validate_checksum=OFF
plugin-load=AUDIT=libaudit_plugin.so

Mysql will start however in the logs still:

```
2017-01-11 13:56:04 31805 [Warning] option 'audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-11 13:56:04 31805 [Warning] option 'plugin-audit-json-file-bufsize': signed value 0 adjusted to 1
2017-01-11 13:56:04 31805 [Note] Audit Plugin: starting up. Version: 1.1.1 , Revision: 660 (64bit). AUDIT plugin interface version: 769 (0x301). MySQL Server version: 5.6.31-log.
2017-01-11 13:56:04 31805 [Note] Audit Plugin: setup_offsets audit_offsets: (null) validate_checksum: 0 offsets_by_version: 1
2017-01-11 13:56:04 31805 [Note] Audit Plugin: mysqld: /usr/sbin/mysqld (b919af973cb0f7c6c7c97a77934deb58)
2017-01-11 13:56:04 31805 [ERROR] Audit Plugin: Offsets: 5.6.31 (f0ca4df6f1b6f3e31aa4a1a94a94d84d) match thread validation check fails with value: 0. Skipping offset.
2017-01-11 13:56:04 31805 [ERROR] Audit Plugin: Offsets: 5.6.31 (f0ca4df6f1b6f3e31aa4a1a94a94d84d) match thread validation check fails with value: 0. Skipping offset.
2017-01-11 13:56:04 31805 [Note] Audit Plugin: Couldn't find proper THD offsets for: 5.6.31-log
2017-01-11 13:56:04 31805 [ERROR] Plugin 'AUDIT' init function returned error.
2017-01-11 13:56:04 31805 [ERROR] Plugin 'AUDIT' registration as a AUDIT failed.
2017-01-11 13:56:04 31805 [Note] Shutting down plugin 'AUDIT'
2017-01-11 13:56:04 31805 [Note] Audit Plugin: deinit
```

this mysql version was installed by my colleague and was taken from: http://releases.galeracluster.com/redhat/6/x86_64/

any other ideas except rebuild from source to extract the offsets?

thanks.

**Comment by megol** [comment] 2017-01-11 13:38
@aharonrobbins could you advice how to rebuild from source to extract the offsets?

thanks.

**Comment by aharonrobbins** [comment] 2017-01-11 13:46
Google leads me to a [link](http://galeracluster.com/documentation-webpages/installmariadbsrc.html) to build Galera Cluster based on MariaDB and another [link](http://galeracluster.com/documentation-webpages/installmysqlsrc.html) to build Galera Cluster based on MySQL but they look similar. I have not reviewed the contents.

HTH

**Comment by guylichtman** [comment] 2017-01-11 21:14
@megol you can run `mysqlbug` to get the compilation options used to build MySQL. 

Another option, which might work, is trying to extract the offsets from the debian distribution. I took a look and their debian distro contains debug symbols. 

Finally, it might be beneficial to suggest to the team maintaining galeracluster to keep the debug symbols (this also helps a lot with various debugging tasks). If they don't want to include it as part of the binary, they can maintain it as a separate package (Percona does this with a debuginfo package).

**Comment by megol** [comment] 2017-01-11 21:35
Thanks guys I will try to take a look at it tomorrow morning when I will be in the office and let you know.

Thanks.

**Comment by guylichtman** [comment] 2017-01-12 08:38
@megol,  Take a look the following comment on an issue of @codership: https://github.com/codership/mysql-wsrep/issues/72#issuecomment-76135271 . It states that binaries should not be stripped. The issue is for debian, which probably explains why debian contains the debug symbols. Not clear what is the status with rpm packages.

@philip-galera , maybe you can provide insight on why rpm packages of mysql on galeracluster.com don't contain symbols. Is this by design? Is there a possibility to include debuginfo packages in this case?

**Comment by aharonrobbins** [comment] 2017-02-13 14:44
Closing this issue.

**Closed by aharonrobbins** 2017-02-13 14:44 UTC

**Comment by subhajit1987** [comment] 2017-02-17 06:54
Please refer my audit issue in Galera MySQL 5.6:

Mcafee audit plugin not working for MySQL Galera 5.6 version #160
